In [1]:
import os 
import pandas as pd
import IPython.display

In [2]:
# for visual studio code
os.chdir('/home/r10222035/boosted_V_ML_test/CNN/')

# Jet

In [2]:
file_name = 'CNN_training_results.csv'
training_results_df = pd.read_csv(file_name)

In [7]:
file_name = 'CNNsq_training_results.csv'
training_results_df = pd.read_csv(file_name)

In [3]:
training_results_df

,kappa,Sample,Model,Overall ACC,time,Train W+W+,Validation W+W+,Test W+W+,W+W+ AUC,W+W+ ACC,...,Train W-Z,Validation W-Z,Test W-Z,W-Z AUC,W-Z ACC,Train W+W-,Validation W+W-,Test W+W-,W+W- AUC,W+W- ACC
0,0.15,10k,CNN,0.208984,2022-11-27 14:43:52.025970,277,34,94,0.597450,0.816406,...,252,34,90,0.531991,0.826172,263,48,91,0.511394,0.822266
1,0.15,10k,CNNsq,0.273438,2022-11-27 15:14:41.893011,277,34,94,0.760053,0.843750,...,252,34,90,0.533254,0.824219,263,48,91,0.481663,0.822266
2,0.15,1000k,CNN,0.451154,2022-11-27 15:20:35.487143,30684,7542,9600,0.859659,0.857787,...,28292,7116,8769,0.736820,0.842089,30752,7732,9725,0.740654,0.830443
3,0.15,1000k,CNNsq,0.379417,2022-11-27 15:51:20.932601,30684,7542,9600,0.829751,0.845575,...,28292,7116,8769,0.686212,0.839935,30752,7732,9725,0.689973,0.826263

In [4]:
def read_sample_size(df):
    col = ['kappa', 'Sample', 'Train W+', 'Train W-', 'Train Z', 'Validation W+', 'Validation W-', 'Validation Z', 'Test W+',	'Test W-', 'Test Z', 'time']
    IPython.display.display(df[col])
    
    cols = ['Train W+', 'Train W-', 'Train Z', 'Test W+', 'Validation W+', 'Validation W-', 'Validation Z', 'Test W-', 'Test Z']
    for i, row in df[cols].iterrows():
        training_set = f"${row['Train W+']//1000}k+{row['Train W-']//1000}k+{row['Train Z']//1000}k$"
        validation_set = f"${row['Validation W+']//1000}k+{row['Validation W-']//1000}k+{row['Validation Z']//1000}k$"
        testing_set = f"${row['Test W+']//1000}k+{row['Test W-']//1000}k+{row['Test Z']//1000}k$"
    
        print(f'{training_set:20} {validation_set:20} {testing_set:20}')
        print(f'{i} {training_set} & {validation_set} & {testing_set}')

def read_training_result(df):
    pd.set_option('display.precision', 3)
    col = ['kappa', 'Sample', 'Overall ACC', 'W+ AUC', 'W+ ACC', 'W- AUC', 'W- ACC', 'Z AUC', 'Z ACC', 'time']
    IPython.display.display(df[col])

In [5]:
read_sample_size(training_results_df)

,kappa,Sample,Train W+,Train W-,Train Z,Validation W+,Validation W-,Validation Z,Test W+,Test W-,Test Z,time
0,0.15,100k,11367,12071,10354,2928,2924,2596,3516,3700,3280,2022-10-05 22:19:39.377108
1,0.15,100k,11367,12071,10354,2928,2924,2596,3516,3700,3280,2022-10-05 22:48:30.039870
2,0.15,700k,80074,84602,72636,20122,21079,17935,24923,26276,22785,2022-10-05 23:13:48.772928
3,0.30,100k,11395,12044,10353,2858,2946,2644,3547,3706,3243,2022-10-05 23:18:13.297071
4,0.30,700k,80250,84492,72570,19863,21028,18245,25013,26440,22531,2022-10-06 00:19:56.449051
5,0.15,1700k,194073,205456,176983,48452,51644,44032,60572,64406,55246,2022-10-06 16:13:31.466257
6,0.30,1700k,194148,205715,176649,48311,51453,44364,60634,64343,55247,2022-10-09 02:56:44.925392
7,0.15,100k-2,25255,26441,20496,6413,6492,5015,7994,8271,6263,2022-10-15 18:12:46.243025
8,0.15,100k-3,31582,32263,30875,7805,8040,7707,9632,10015,9537,2022-10-15 23:28:18.038020
9,0.15,1000k-fish,61872,65557,102971,15327,16220,25797,19212,20180,32288,2022-10-29 21:05:54.516036
10,0.15,1000k-fish,61872,65557,102971,15327,16220,25797,19212,20180,32288,2022-10-29 21:35:45.511849
11,0.15,1000k-fish-2,313370,323897,307373,78299,81155,76578,97750,101347,95815,2022-10-30 03:25:14.842816
12,0.15,1000k,313068,323475,307073,78176,80581,76763,97518,100926,96468,2022-10-30 18:25:41.058634
13,0.15,500k-J,112415,116276,101037,27914,29110,25408,34976,36491,31445,2022-11-06 14:22:08.844832
14,0.15,1000k-J,224518,232960,201978,56078,58367,50419,69783,72784,63257,2022-11-06 21:45:01.418641
15,0.15,1000k,223683,232549,202200,56028,57982,50342,69804,72691,62817,2022-11-17 15:23:30.882417
16,0.15,1000k,223742,232980,201710,56002,57682,50668,69760,72578,62974,2022-11-18 10:46:56.206453

$11k+12k+10k$        $2k+2k+2k$           $3k+3k+3k$
0 $11k+12k+10k$ & $2k+2k+2k$ & $3k+3k+3k$
$11k+12k+10k$        $2k+2k+2k$           $3k+3k+3k$
1 $11k+12k+10k$ & $2k+2k+2k$ & $3k+3k+3k$
$80k+84k+72k$        $20k+21k+17k$        $24k+26k+22k$
2 $80k+84k+72k$ & $20k+21k+17k$ & $24k+26k+22k$
$11k+12k+10k$        $2k+2k+2k$           $3k+3k+3k$
3 $11k+12k+10k$ & $2k+2k+2k$ & $3k+3k+3k$
$80k+84k+72k$        $19k+21k+18k$        $25k+26k+22k$
4 $80k+84k+72k$ & $19k+21k+18k$ & $25k+26k+22k$
$194k+205k+176k$     $48k+51k+44k$        $60k+64k+55k$
5 $194k+205k+176k$ & $48k+51k+44k$ & $60k+64k+55k$
$194k+205k+176k$     $48k+51k+44k$        $60k+64k+55k$
6 $194k+205k+176k$ & $48k+51k+44k$ & $60k+64k+55k$
$25k+26k+20k$        $6k+6k+5k$           $7k+8k+6k$
7 $25k+26k+20k$ & $6k+6k+5k$ & $7k+8k+6k$
$31k+32k+30k$        $7k+8k+7k$           $9k+10k+9k$
8 $31k+32k+30k$ & $7k+8k+7k$ & $9k+10k+9k$
$61k+65k+102k$       $15k+16k+25k$        $19k+20k+32k$
9 $61k+65k+102k$ & $15k+16k+25k$ & $19k+20k+32k$
$61k+65k+102k$       $15k+16k+25k$        $19k+20k+32k$
10 $61k+65k+102k$ & $15k+16k+25k$ & $19k+20k+32k$
$313k+323k+307k$     $78k+81k+76k$        $97k+101k+95k$
11 $313k+323k+307k$ & $78k+81k+76k$ & $97k+101k+95k$
$313k+323k+307k$     $78k+80k+76k$        $97k+100k+96k$
12 $313k+323k+307k$ & $78k+80k+76k$ & $97k+100k+96k$
$112k+116k+101k$     $27k+29k+25k$        $34k+36k+31k$
13 $112k+116k+101k$ & $27k+29k+25k$ & $34k+36k+31k$
$224k+232k+201k$     $56k+58k+50k$        $69k+72k+63k$
14 $224k+232k+201k$ & $56k+58k+50k$ & $69k+72k+63k$
$223k+232k+202k$     $56k+57k+50k$        $69k+72k+62k$
15 $223k+232k+202k$ & $56k+57k+50k$ & $69k+72k+62k$
$223k+232k+201k$     $56k+57k+50k$        $69k+72k+62k$
16 $223k+232k+201k$ & $56k+57k+50k$ & $69k+72k+62k$

In [9]:
read_training_result(training_results_df)

,kappa,Sample,Overall ACC,W+ AUC,W+ ACC,W- AUC,W- ACC,Z AUC,Z ACC,time
0,0.15,100k,0.642,0.828,0.773,0.831,0.773,0.801,0.780,2022-10-06 13:34:01.737784
1,0.30,100k,0.645,0.823,0.773,0.828,0.773,0.802,0.784,2022-10-08 21:43:52.605197
2,0.15,700k,0.677,0.848,0.792,0.848,0.786,0.842,0.806,2022-10-08 22:51:44.972389
3,0.30,700k,0.669,0.842,0.788,0.843,0.780,0.839,0.804,2022-10-08 23:28:55.541340
4,0.15,1700k,0.674,0.848,0.792,0.849,0.785,0.843,0.807,2022-10-09 03:36:19.685603
5,0.30,1700k,0.675,0.846,0.790,0.847,0.784,0.845,0.808,2022-10-09 12:38:44.354692
6,0.15,700k,0.678,0.847,0.792,0.848,0.786,0.842,0.806,2022-10-09 14:19:25.114874
7,0.15,100k-2,0.655,0.834,0.777,0.836,0.777,0.810,0.798,2022-10-15 18:23:25.939747
8,0.15,1000k,0.684,0.855,0.797,0.854,0.793,0.835,0.797,2022-10-31 00:24:43.709031
9,0.15,500k-J,0.693,0.860,0.797,0.859,0.794,0.838,0.816,2022-11-06 15:04:18.335144
10,0.15,1000k-J,0.698,0.863,0.800,0.862,0.797,0.844,0.818,2022-11-06 22:27:14.875470
11,0.15,1000k,0.683,0.856,0.795,0.855,0.790,0.824,0.802,2022-11-17 16:55:44.264813
12,0.15,1000k,0.685,0.856,0.794,0.855,0.791,0.823,0.802,2022-11-18 11:40:52.970880

# Event

In [2]:
file_name = 'event_training_results.csv'
training_results_df = pd.read_csv(file_name)

In [3]:
training_results_df

,kappa,Sample,Model,Overall ACC,time,Train W+W+,Validation W+W+,Test W+W+,W+W+ AUC,W+W+ ACC,...,Train W-Z,Validation W-Z,Test W-Z,W-Z AUC,W-Z ACC,Train W+W-,Validation W+W-,Test W+W-,W+W- AUC,W+W- ACC
0,0.15,10k,CNN,0.208984,2022-11-27 14:43:52.025970,277,34,94,0.597450,0.816406,...,252,34,90,0.531991,0.826172,263,48,91,0.511394,0.822266
1,0.15,10k,CNNsq,0.273438,2022-11-27 15:14:41.893011,277,34,94,0.760053,0.843750,...,252,34,90,0.533254,0.824219,263,48,91,0.481663,0.822266
2,0.15,1000k,CNN,0.451154,2022-11-27 15:20:35.487143,30684,7542,9600,0.859659,0.857787,...,28292,7116,8769,0.736820,0.842089,30752,7732,9725,0.740654,0.830443
3,0.15,1000k,CNNsq,0.379417,2022-11-27 15:51:20.932601,30684,7542,9600,0.829751,0.845575,...,28292,7116,8769,0.686212,0.839935,30752,7732,9725,0.689973,0.826263
4,0.15,1000k,CNNsq,0.379819,2022-11-27 17:01:07.079046,30684,7542,9600,0.829435,0.845247,...,28292,7116,8769,0.686224,0.840026,30752,7732,9725,0.689391,0.826008

In [5]:
event_type = ['W+W+', 'W-W-', 'ZZ', 'W+Z', 'W-Z', 'W+W-']
    
def read_event_sample_size(df):
    col = ['kappa', 'Sample']
    col.extend([f'Train {_type}' for _type in event_type])
    col.extend([f'Validation {_type}' for _type in event_type])
    col.extend([f'Test {_type}' for _type in event_type])
    col.append('time')
    IPython.display.display(df[col])
    
#     cols = ['Train W+', 'Train W-', 'Train Z', 'Test W+', 'Validation W+', 'Validation W-', 'Validation Z', 'Test W-', 'Test Z']
#     for i, row in df[cols].iterrows():
#         training_set = f"${row['Train W+']//1000}k+{row['Train W-']//1000}k+{row['Train Z']//1000}k$"
#         validation_set = f"${row['Validation W+']//1000}k+{row['Validation W-']//1000}k+{row['Validation Z']//1000}k$"
#         testing_set = f"${row['Test W+']//1000}k+{row['Test W-']//1000}k+{row['Test Z']//1000}k$"
    
#         print(f'{training_set:20} {validation_set:20} {testing_set:20}')
#         print(f'{i} {training_set} & {validation_set} & {testing_set}')

def read_event_training_result(df):
    pd.set_option('display.precision', 3)
    col = ['kappa', 'Sample', 'Model', 'Overall ACC',]
    for _type in event_type:
        col.append(f'{_type} AUC')
        col.append(f'{_type} ACC')
        
    col.append('time')    
    IPython.display.display(df[col])

In [6]:
read_event_sample_size(training_results_df)

,kappa,Sample,Train W+W+,Train W-W-,Train ZZ,Train W+Z,Train W-Z,Train W+W-,Validation W+W+,Validation W-W-,...,Validation W+Z,Validation W-Z,Validation W+W-,Test W+W+,Test W-W-,Test ZZ,Test W+Z,Test W-Z,Test W+W-,time
0,0.15,10k,277,291,222,231,252,263,34,57,...,43,34,48,94,91,74,72,90,91,2022-11-27 14:43:52.025970
1,0.15,10k,277,291,222,231,252,263,34,57,...,43,34,48,94,91,74,72,90,91,2022-11-27 15:14:41.893011
2,0.15,1000k,30684,32899,25012,27465,28292,30752,7542,8280,...,6713,7116,7732,9600,10219,7818,8653,8769,9725,2022-11-27 15:20:35.487143
3,0.15,1000k,30684,32899,25012,27465,28292,30752,7542,8280,...,6713,7116,7732,9600,10219,7818,8653,8769,9725,2022-11-27 15:51:20.932601
4,0.15,1000k,30684,32899,25012,27465,28292,30752,7542,8280,...,6713,7116,7732,9600,10219,7818,8653,8769,9725,2022-11-27 17:01:07.079046

In [8]:
read_event_training_result(training_results_df)

,kappa,Sample,Model,Overall ACC,W+W+ AUC,W+W+ ACC,W-W- AUC,W-W- ACC,ZZ AUC,ZZ ACC,W+Z AUC,W+Z ACC,W-Z AUC,W-Z ACC,W+W- AUC,W+W- ACC,time
0,0.15,10k,CNN,0.209,0.597,0.816,0.651,0.822,0.563,0.855,0.475,0.859,0.532,0.826,0.511,0.822,2022-11-27 14:43:52.025970
1,0.15,10k,CNNsq,0.273,0.760,0.844,0.728,0.838,0.569,0.859,0.559,0.859,0.533,0.824,0.482,0.822,2022-11-27 15:14:41.893011
2,0.15,1000k,CNN,0.451,0.860,0.858,0.855,0.850,0.797,0.868,0.740,0.845,0.737,0.842,0.741,0.830,2022-11-27 15:20:35.487143
3,0.15,1000k,CNNsq,0.379,0.830,0.846,0.822,0.837,0.684,0.858,0.687,0.842,0.686,0.840,0.690,0.826,2022-11-27 15:51:20.932601